version: '3'
services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: thePassword
    expose:
      - '3306'
  eureka-server:
    image: eurekaimage
    restart: on-failure
    ports:
      - 8761:8761
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mysql
  product:
    image: productimage
    restart: on-failure
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - eureka-server
    ports:
      - 8081:8081
  customer:
    image: customerimage
    restart: on-failure
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - product
    ports:
      - 8082:8082
  credit:
    image: creditimage
    restart: on-failure
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - eureka-server
    ports:
      - 8083:8083
volumes:
    mysql_data: {}