server:
  port: 0
spring:
  application:
    name: Product-Service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: springuser
    password: thePassword 
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/      